<?

$lang = $this->layout()->lang;
?>

<ul>
<? //var_dump($this->container->getPage());
//$active = $this->findActive($this->container);
//if(count($active['pages'])) foreach($active['pages'] as $page){
//   $label = $this->translate($page->getLabel());
//   $page->setParams(['lang' => $lang]);
//   $href = $page->getHref();?>
<!--   <li--><?//=$page->isActive()? ' class="active"': ''?><!-->-->
<!--      <a href="--><?//=$href?><!--" title="--><?//=$label?><!--">-->
<!--         --><?//=$label?>
<!--      </a>-->
<!--   </li>-->
<?// }?>
</ul>

